# Advocate PRO pipeline description

image: composer:2.0

pipelines:
  branches:
    master:
      - step:
          name: Test
          caches:
            - composer
          script: # Modify the commands below to build your repository.
            - mv .env.exemple .env
            - composer install
            - php artisan key:generate
            - ./vendor/bin/phpunit
          artifacts: # defining the artifacts to be passed to each future step.
            - vendor/**
      - step:
          name: Compile
          image: node:lts
          caches:
            - node
          script:
            - mv .env.exemple .env
            - npm install
            - npm run dev
          artifacts: # defining the artifacts to be passed to each future step.
            - public/**
      - step:
          name: Deploy
          deployment: staging
          script:
            # whatever .env file is referenced in the ENV
            - echo $ENV_FILE | base64 --decode --ignore-garbage > .env
            - pipe: atlassian/rsync-deploy:0.4.4
              variables:
                USER: $REMOTE_USER
                SERVER: $REMOTE_SERVER
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: '.'
                # dont show file list and exclude (bitbucket, git, node_modules) files
                EXTRA_ARGS: '-arvz --delete --quiet --exclude=.git* --exclude=.bitbucket --exclude=bitbucket-pipelines.yml --exclude=node_modules'
