# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: Test
            trigger: manual
            script:
              - mv .env.example .env
              - composer install
              - ./vendor/bin/phpunit
            caches:
              - composer
        - step:
            name: Deploy
            deployment: Staging
            script:
              - pipe: atlassian/ftp-deploy:0.3.5
                variables:
                  USER: $FTP_USER
                  PASSWORD: $FTP_PASS
                  SERVER: $FTP_HOST
                  REMOTE_PATH: $FTP_PATH
                  DELETE_FLAG: 'false' # Don't delete existing files
                  EXTRA_ARGS: "--exclude=.bitbucket/ --exclude=.git/ --exclude=bitbucket-pipelines.yml --exclude=.gitignore" # Ignore these
