# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: composer:2.0


pipelines:
  default:
    - parallel:
        - step:
            name: Test
            trigger: manual
            script:
              - mv .env.example .env
              - composer install
              - ./vendor/bin/phpunit
            caches:
              - composer
        - step:
            name: Deploy
            deployment: Staging
            script:
              - pipe: atlassian/ftp-deploy:0.3.5
                variables:
                  USER: "$USER"
                  PASSWORD: "$PASS"
                  SERVER: "$HOST"
                  REMOTE_PATH: "$PATH"
